# Generated by Django 3.2.13 on 2022-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
